language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer install
  - find vendor/phpunit/ -name "build" -exec rm -rf {} \; || true

script:
  - ./vendor/bin/phpcs --standard=ruleset.xml ./src/
  - phpunit
